language: c
sudo: false
addons:
  apt:
    packages:
      - libssl-dev
      - tcl-dev
      - libtomcrypt-dev
env:
  global:
    - CFLAGS="-O2 -fno-strict-aliasing
              -DSQLITE_HAS_CODEC -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_COLUMN_METADATA
              -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT=1 -DSQLITE_MAX_VARIABLE_NUMBER=250000"
  matrix:
    - CRYPTO_LIB=libtomcrypt
    - CRYPTO_LIB=openssl LDFLAGS="-lcrypto"
script:
  - ./configure --enable-tempstore=yes --with-crypto-lib=$CRYPTO_LIB
  - make
  - make test
